import type { NewItem } from "@/contexts/trading/shared/infrastructure/csgoempire/ws-events/new-item";

export const newItem: NewItem[] = [
    {
        auction_ends_at: 1738080016,
        auction_highest_bid: null,
        auction_highest_bidder: null,
        auction_number_of_bids: 0,
        icon_url:
            "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou-6kejhjxszFJTwW09-vloWZh-L6OITck29Y_cg_0r_HrY2m2ATmqhBlYT-nd9TDdFNoZQvWrla2xL29gMDpuM6cnHQ2vj5iuyhtZhH0GA",
        is_commodity: false,
        market_name: "M4A4 | Cyber Security (Field-Tested)",
        market_value: 3656,
        name_color: "D2D2D2",
        price_is_unreliable: false,
        suggested_price: 3801,
        published_at: "2025-01-28T15:57:17.272965Z",
        id: 288767047,
        marketplace_privacy_protection_level: "strict",
        above_recommended_price: -4.05,
        purchase_price: 3656,
        item_search: {
            category: "Weapon",
            type: "Rifle",
            sub_type: "M4A4",
            rarity: "Classified",
        },
        wear_name: "Field-Tested",
        depositor_stats: {
            delivery_rate_recent: null,
            delivery_rate_long: null,
            delivery_time_minutes_recent: null,
            delivery_time_minutes_long: null,
            delivery_rate_status: "poor",
            steam_level_min_range: null,
            steam_level_max_range: null,
            user_has_trade_notifications_enabled: true,
            user_online_status: 1,
        },
    },
    {
        auction_ends_at: null,
        auction_highest_bid: null,
        auction_highest_bidder: null,
        auction_number_of_bids: 0,
        blue_percentage: null,
        fade_percentage: null,
        icon_url:
            "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpovbSsLQJf1ObcTjxP09u3mY2KqPP7I6vdk3lu-M1wmeyTyoD8j1yg5RZrY26iItOTewQ3N1DVqFG9yObrh8W8uZnBmnRm6XYi53vfyhCxgBFSLrs4Q3CxbRA",
        is_commodity: false,
        market_name: "★ Gut Knife | Gamma Doppler (Factory New) - Phase 2",
        market_value: 46709,
        name_color: "8650AC",
        preview_id: "0651e9bdeae9",
        price_is_unreliable: false,
        stickers: [],
        suggested_price: 43271,
        wear: 0.008,
        published_at: "2025-01-28T17:11:28.916993Z",
        id: 288775401,
        marketplace_privacy_protection_level: "base",
        above_recommended_price: 8.42,
        purchase_price: 46709,
        item_search: {
            category: "Weapon",
            type: "Knife",
            sub_type: "Gut Knife",
            rarity: "Covert",
        },
        wear_name: "Factory New",
        depositor_stats: {
            delivery_rate_recent: 1,
            delivery_rate_long: 1,
            delivery_time_minutes_recent: 1,
            delivery_time_minutes_long: 1,
            delivery_rate_status: null,
            steam_level_min_range: 0,
            steam_level_max_range: 4,
            user_has_trade_notifications_enabled: false,
            user_online_status: 1,
        },
    },
    {
        auction_ends_at: 1738084482,
        auction_highest_bid: null,
        auction_highest_bidder: null,
        auction_number_of_bids: 0,
        blue_percentage: null,
        fade_percentage: null,
        icon_url:
            "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot621FAR17PLfYQJD_9W7m5a0mvLwOq7c2DMBupQn2eqVotqkiwHiqhdlMmigJtOWJwE5Zw3X8wS-yea8jcDo7c7XiSw0g89L9us",
        is_commodity: false,
        market_name: "AWP | Asiimov (Well-Worn)",
        market_value: 16300,
        name_color: "D2D2D2",
        preview_id: "11076784be00",
        price_is_unreliable: false,
        stickers: [
            {
                wear: null,
                name: "Fnatic | Rio 2022",
                image: "https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXQ9QVcJY8gulRPRUOCF7b_mMndR15LKQVFsb_rflBigKaQdGxGvIm1zdHcla6lY-PQkzxXscYi0uuUoYqkjFDtqkJra3ezetGf5hhLtg",
            },
            {
                wear: null,
                name: "Fnatic | Rio 2022",
                image: "https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXQ9QVcJY8gulRPRUOCF7b_mMndR15LKQVFsb_rflBigKaQdGxGvIm1zdHcla6lY-PQkzxXscYi0uuUoYqkjFDtqkJra3ezetGf5hhLtg",
            },
            {
                wear: null,
                name: "Fnatic (Glitter) | Paris 2023",
                image: "https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXQ9QVcJY8gulRNTV7ZVLb9hZycVVNgJjtQurOxPwJy7P_JYzpHoti3wNbflqShZ7jVxj4C7Jwk2r7AoY_32lG2qEY6Zmild4KSJwc9ZA3Oug_pJVFYabg",
            },
            {
                wear: null,
                name: "Fnatic (Glitter) | Paris 2023",
                image: "https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXQ9QVcJY8gulRNTV7ZVLb9hZycVVNgJjtQurOxPwJy7P_JYzpHoti3wNbflqShZ7jVxj4C7Jwk2r7AoY_32lG2qEY6Zmild4KSJwc9ZA3Oug_pJVFYabg",
            },
        ],
        suggested_price: 16643,
        wear: 0.398,
        published_at: "2025-01-28T17:11:43.378843Z",
        id: 288775415,
        marketplace_privacy_protection_level: "base",
        above_recommended_price: -2.18,
        purchase_price: 16300,
        item_search: {
            category: "Weapon",
            type: "Sniper Rifle",
            sub_type: "AWP",
            rarity: "Covert",
        },
        wear_name: "Well-Worn",
        depositor_stats: {
            delivery_rate_recent: 1,
            delivery_rate_long: null,
            delivery_time_minutes_recent: 237,
            delivery_time_minutes_long: null,
            delivery_rate_status: null,
            steam_level_min_range: 21,
            steam_level_max_range: 40,
            user_has_trade_notifications_enabled: false,
            user_online_status: 1,
        },
    },
];
